{
 "title": "Prometheus Proxy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Maximum Scrape Payload",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "prometheus_proxy_scrape_payload_bytes_max",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(prometheus_proxy_scrape_payload_bytes_count[1m]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "RSocket Request/Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rsocket_request_response_seconds_count{signal_type=\"ON_COMPLETE\"}[1m])",
     "legendFormat": "complete"
    },
    {
     "expr": "rate(rsocket_request_response_seconds_count{signal_type=\"CANCEL\"}[1m])",
     "legendFormat": "cancel"
    },
    {
     "expr": "rate(rsocket_request_response_seconds_count{signal_type=\"ON_ERROR\"}[1m])",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_proxy_scrape_active_connections",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Prometheus Scrapes of Individual Processes by Outcome",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_proxy_scrape_seconds_count{outcome=\"success\"}[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(prometheus_proxy_scrape_seconds_count{outcome=\"closed\"}[1m])",
     "legendFormat": "closed"
    },
    {
     "expr": "rate(prometheus_proxy_scrape_seconds_count{outcome=\"error\"}[1m])",
     "legendFormat": "error"
    }
   ]
  }
 ]
}